Error occured while generating Report Output "Radial Chart"
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last):
 Report Output "Radial Chart" <v1>, line 28, in <definition>
        10 |         fig.add_trace(
        11 |             go.Scatterpolar(
        12 |                 r=df["Mean Score"].tolist() + [df["Mean Score"].tolist()[0]],
(...)
        16 |             )
        17 |         )
        19 |     fig.update_layout(
        20 |         title="<b>Evaluation Scores Across Multiple Risk Dimensions</b><br>(1: Worst Case, 5: Best Case)",
        21 |         polar=dict(radialaxis=dict(visible=True, range=[0, 5])),
        22 |         showlegend=len(raw_output) > 1,
        23 |         title_x=0.5,
        24 |     )
        25 |     return fig
---->   28 | return radial_chart(raw_output)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
    Local variables:
      job           = <Job job_type="Simulati...: Jun-20-2025 02:21 PM">
      raw_output    = {'metrics_df': pandas.DataFrame[Metric: object, Score Reviewer-1: float64, Explanation Reviewer-1: object, Response Reviewer-1: object, Tags Reviewer-1: object, Mean Score: float64, common_tags: object], 'overall_readiness': 66.67, 'pointers_for_improvement': 'Based on a thorough an...iased in all scenarios.', 'tags_df': pandas.DataFrame[Metric: object, Category: object, is_fine: int64]}
 Report Output "Radial Chart" <v1>, line 8, in radial_chart
         4 | def radial_chart(output_dict):
         5 |     fig = go.Figure()
         7 |     for prompt_name, prompt_data in output_dict.items():
---->    8 |         df = prompt_data["metrics_df"].copy(deep=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
         9 |         df = df[0 : len(df) - 1]
    Local variables:
      output_dict   = {'metrics_df': pandas.DataFrame[Metric: object, Score Reviewer-1: float64, Explanation Reviewer-1: object, Response Reviewer-1: object, Tags Reviewer-1: object, Mean Score: float64, common_tags: object], 'overall_readiness': 66.67, 'pointers_for_improvement': 'Based on a thorough an...iased in all scenarios.', 'tags_df': pandas.DataFrame[Metric: object, Category: object, is_fine: int64]}
      fig           = Figure({
                          'data': []...: {'template': '...'}
                      })
      prompt_name   = 'overall_readiness'
      prompt_data   = 66.67
IndexError: invalid index to scalar variable.