
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last):
 Report Additional Figure "Score Distribution" <v1>, line 23, in <definition>
         7 |     df_copy["fact_check_status"] = pd.Categorical(
         8 |         df_copy["fact_check_status"], categories=all_possible_scores, ordered=True
         9 |     )
        11 |     summary_table = pd.crosstab(
        12 |         index=df_copy["intent"],
        13 |         columns=df_copy["fact_check_status"],
(...)
        18 |         margins_name="Total",
        19 |     )
        21 |     return summary_table
---->   23 | df = raw_output[job.current.name]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        25 | bucket_display_map = {
        26 |     "VERY LOW": "Very Low Confidence",
        27 |     "LOW": "Low Confidence",
(...)
        30 |     "VERY HIGH": "Very High Confidence",
        31 | }
    Local variables:
      job           = <Job job_type="Simulati..."Example Dashboard Run">
      raw_output    = {'CorridorPlatforms Bot': pandas.DataFrame[output: object, intent: object, length: object, ground_truth: object, group_id: object, grammar_error: object, urgent: object, polite: object, category: object, query_category: object, scenario: object, evaluation: object, user_message: object, history: object, context: object, response: object, context_logs: object, db_output: object, cosine_similarity: float64, temp_llm_fact: object, fact_check_status: object, fact_check_reason: object, fact_check_logs: object, temp_llm_similarity: object, llm_answer_relevancy: object, llm_answer_relevancy_reason: object]}
KeyError: 'CorridorPlatforms Website Bot'
